---
- name: Add Docker CE repo
  get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"

- name: Install Docker CE
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: true
    state: started
