---
- name: Configure zeropad VM
  hosts: all
  become: true
  vars:
    domain: "zeropad.dev"
    github_owner: "victorfariafernandes"
    block_device: /dev/sdb
    data_mount: /data
    oci_namespace: "{{ lookup('env', 'OCI_NAMESPACE') }}"
    backend_replicas: 2
    backend_memory: "256m"
    backend_memory_reservation: "128m"

  roles:
    - role: volume
      tags: volume
    - role: docker
      tags: docker
    - role: backend
      tags: backend
    - role: frontend
      tags: frontend
    - role: caddy
      tags: caddy
