---
- name: Show frontend version
  debug:
    msg: "Frontend deploying version: {{ release_tag }}"

- name: Create frontend directory
  file:
    path: /data/frontend
    state: directory
    mode: "0755"

- name: Download frontend release tarball
  get_url:
    url: "https://github.com/{{ github_owner }}/dopad/releases/download/{{ release_tag }}/frontend-{{ release_tag }}.tar.gz"
    dest: "/tmp/frontend-{{ release_tag }}.tar.gz"
    mode: "0644"

- name: Extract frontend
  unarchive:
    src: "/tmp/frontend-{{ release_tag }}.tar.gz"
    dest: /data/frontend
    remote_src: true
